#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,2,5,8,31,41,44,47,60,62&i=1,2,3,4,18,19,20,21,34&v=4,5,-1,255,27,25,26,-1,13 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, XPT2046_Touchscreen */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL			DSP_ILI9488
#define I2S_DOUT			255
#define VS1053_CS			27
#define TS_MODEL			TS_MODEL_XPT2046


#endif
